### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Pie-Not-Lie** [LGatodu47/ScreenshotViewer#43]
Needs updated to the latest version

**Comment by Legendmanj** [comment]
agree

+ upvote

**Comment by Felix14-v2** [comment]
Relevant crash report info:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'screenshot_viewer'!
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalAccessError: class io.github.lgatodu47.screenshot_viewer.ScreenshotViewer tried to access private method 'void net.minecraft.util.Identifier.<init>(java.lang.String, java.lang.String)' (io.github.lgatodu47.screenshot_viewer.ScreenshotViewer and net.minecraft.util.Identifier are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @8bd1b6a)
	at io.github.lgatodu47.screenshot_viewer.ScreenshotViewer.<clinit>(ScreenshotViewer.java:54)
	at java.base@21.0.3/java.lang.Class.forName0(Native Method)
	at java.base@21.0.3/java.lang.Class.forName(Class.java:534)
	at java.base@21.0.3/java.lang.Class.forName(Class.java:513)
	at app//net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at app//net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:477)
```

**Comment by notrohit1702** [comment]
https://modrinth.com/mod/screenshot-viewer/version/1.21-fabric-1
